services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn yourprojectname.wsgi
    envVars:
      - key: DEBUG
        value: "False"
